# --------PRODUCTION-----------
version: '5'
services:
  redis:
    image: redis:alpine
    restart: on-failure
    ports:
      - "6379:6379"
  db:
    image: postgres:12.14
    restart: always
    environment:
      POSTGRES_PASSWORD: asdf
      POSTGRES_DB: dating_app
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./backend/backend
    command: daphne backend.asgi:application -b 0.0.0.0 -p 8000
    ports:
      - "8000:8000"
    volumes:
      - mediafiles:/usr/app/backend/static
    depends_on:
      - db
  nginx:
    restart: unless-stopped
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf
      - mediafiles:/mediafiles
    depends_on:
      - backend
volumes:
  mediafiles:


# ------TEST----------
# version: '3'
# services:
#   redis:
#     image: redis:alpine
#     restart: on-failure
#     ports:
#       - "6379:6379"
#   backend:
#     build: 
#       context: ./backend/backend
#     network_mode: "host"
#   frontend:
#     build:
#       context: ./frontend/frontend
#     ports:
#       "3000:3000"
#     volumes:


  # admin:
  #   restart: on-failure
  #   build: ./admin
  #   ports:
  #     - "3001:3000"
  # my_postgres_server:
  #   restart: on-failure
  #   image: 'postgres:12.14'