// export const baseUrl = "http://127.0.0.1:8000/api/";
export const baseUrl = "https://www.koode.live/api/";
// export const baseimageUrl = "http://127.0.0.1:8000/static";
export const baseimageUrl = "https://www.koode.live/media";
// export const baseWSurl = "ws://localhost:8000/ws/"
export const baseWSurl = "wss://www.koode.live/ws/"

export const verifyToken = "verifyToken";
export const signup = "signup/";
export const getUser = "getUser/";
export const getAppUsers = "getAppUsers/";
export const userProfiles = "userProfiles/"
export const profileDetails = "profileDetails/";
export const editAbout = "editAbout/";
export const editWorkEdu = "editWorkEdu/";
export const editZodiac = "editZodiac/";
export const addImage1 = "addImage1/";
export const userLiked = "userLiked/";
export const userMatches = "userMatches/";
export const userNotifications = "userNotifications/";
export const userChats = "userChats/";
export const getUserMessages = "getUserMessages/";
export const filterBy = "filterBy/";
export const searchUsers = "searchUsers/";
export const getMatches = "getMatches/";
